// const mongoose = require("mongoose");
// const Recommendation = require("../models/recommendation");
// require("dotenv").config();

// const recommendations = [
//   {
//     emotion: "joy",
//     bodyType: "slim",
//     skinTone: "medium",
//     gender: "non-binary",
//     bestPose: "Relaxed shoulders with soft eye contact",
//     lightingTips: "Use natural daylight to highlight your features.",
//     captionIdeas: [
//       "Joy in the moment 🌟",
//       "Let your light shine ✨",
//       "This smile says it all 😄",
//     ],
//     hashtagSuggestions: ["#joymood", "#shinebright", "#expressyourself"],
//     platforms: [{ name: "Instagram", bestPostTime: "6:00 PM" }],
//   },
//   {
//     emotion: "sorrow",
//     bodyType: "curvy",
//     skinTone: "light",
//     gender: "woman",
//     bestPose: "Gazing down with soft lighting",
//     lightingTips: "Use shadows for a more cinematic feel.",
//     captionIdeas: [
//       "Even sadness has beauty 🌫️",
//       "Moments of silence speak loudest.",
//       "Healing in stillness 💭",
//     ],
//     hashtagSuggestions: ["#moodyaesthetic", "#emotionalvibes", "#softfocus"],
//     platforms: [{ name: "Tumblr", bestPostTime: "9:00 PM" }],
//   },
//   {
//     emotion: "anger",
//     bodyType: "athletic",
//     skinTone: "dark",
//     gender: "man",
//     bestPose: "Direct stare with bold posture",
//     lightingTips: "High-contrast lighting to highlight intensity.",
//     captionIdeas: [
//       "Power is in control 🔥",
//       "Let your fire speak.",
//       "Silence is louder than words 💣",
//     ],
//     hashtagSuggestions: ["#rawemotion", "#strengthwithin", "#boldlook"],
//     platforms: [{ name: "TikTok", bestPostTime: "7:00 PM" }],
//   },
//   {
//     emotion: "surprise",
//     bodyType: "petite",
//     skinTone: "tan",
//     gender: "woman",
//     bestPose: "Hands covering mouth, wide eyes",
//     lightingTips: "Soft ambient light adds playful tone.",
//     captionIdeas: [
//       "Didn't see that coming! 😲",
//       "Caught in the moment ✨",
//       "Surprises keep life exciting!",
//     ],
//     hashtagSuggestions: ["#unexpected", "#playfulpose", "#realreaction"],
//     platforms: [{ name: "Instagram", bestPostTime: "5:00 PM" }],
//   },
//   {
//     emotion: "neutral",
//     bodyType: "any",
//     skinTone: "any",
//     gender: "any",
//     bestPose: "Profile angle with natural expression",
//     lightingTips: "Even lighting with no harsh shadows.",
//     captionIdeas: [
//       "Balanced and calm.",
//       "Let the vibe speak for itself 🌀",
//       "Simplicity is a statement.",
//     ],
//     hashtagSuggestions: ["#chillmood", "#minimalenergy", "#naturalpose"],
//     platforms: [{ name: "Pinterest", bestPostTime: "10:00 AM" }],
//   },
//   {
//     emotion: "joy",
//     bodyType: "curvy",
//     skinTone: "dark",
//     gender: "woman",
//     bestPose: "Laughing with head tilted back",
//     lightingTips: "Golden hour adds magic.",
//     captionIdeas: [
//       "Smiles that light up a room 🌞",
//       "Golden hour glow ✨",
//       "Happiness looks good on me.",
//     ],
//     hashtagSuggestions: [
//       "#confidentbeauty",
//       "#joyfulenergy",
//       "#curvyaesthetic",
//     ],
//     platforms: [{ name: "YouTube", bestPostTime: "12:00 PM" }],
//   },
//   {
//     emotion: "surprise",
//     bodyType: "athletic",
//     skinTone: "medium",
//     gender: "man",
//     bestPose: "Eyes wide, playful lean forward",
//     lightingTips: "Soft backlight for energy.",
//     captionIdeas: [
//       "Guess what just happened?! 👀",
//       "Life’s full of surprises!",
//       "Shock and awe 💥",
//     ],
//     hashtagSuggestions: ["#unexpectedvibes", "#funreaction", "#energymoment"],
//     platforms: [{ name: "TikTok", bestPostTime: "4:30 PM" }],
//   },
//   {
//     emotion: "anger",
//     bodyType: "slim",
//     skinTone: "light",
//     gender: "non-binary",
//     bestPose: "Side profile with serious expression",
//     lightingTips: "Use shadows across face.",
//     captionIdeas: [
//       "Calm on the outside, fire within 🔥",
//       "Controlled chaos.",
//       "Speak with your presence.",
//     ],
//     hashtagSuggestions: ["#vibespeak", "#fiercepose", "#stillstrong"],
//     platforms: [{ name: "Instagram", bestPostTime: "8:00 PM" }],
//   },
//   {
//     emotion: "joy",
//     bodyType: "athletic",
//     skinTone: "tan",
//     gender: "man",
//     bestPose: "Mid-laugh, dynamic movement",
//     lightingTips: "Use daylight with a vibrant background.",
//     captionIdeas: [
//       "Catch me in a good mood 😄",
//       "Every day’s a win 🏆",
//       "Move with energy!",
//     ],
//     hashtagSuggestions: ["#feelgoodvibes", "#happymotion", "#positiveenergy"],
//     platforms: [{ name: "Instagram", bestPostTime: "5:30 PM" }],
//   },
//   {
//     emotion: "neutral",
//     bodyType: "slim",
//     skinTone: "light",
//     gender: "woman",
//     bestPose: "Sitting on a chair, looking away from camera",
//     lightingTips: "Natural window light, no editing.",
//     captionIdeas: [
//       "Quietly confident.",
//       "Soft energy, loud presence.",
//       "Mood: undefined.",
//     ],
//     hashtagSuggestions: ["#softneutral", "#simplestyling", "#undisturbed"],
//     platforms: [{ name: "Tumblr", bestPostTime: "11:00 PM" }],
//   },
//   {
//     emotion: "sorrow",
//     bodyType: "petite",
//     skinTone: "pale",
//     gender: "non-binary",
//     bestPose: "Curled posture with minimal eye contact",
//     lightingTips: "Cool-toned lighting works best.",
//     captionIdeas: [
//       "In the quiet, I find myself.",
//       "Not every day is bright.",
//       "Honesty is beautiful too.",
//     ],
//     hashtagSuggestions: ["#emotionaldepth", "#fragilebeauty", "#authenticself"],
//     platforms: [{ name: "Twitter", bestPostTime: "2:00 PM" }],
//   },
//   {
//     emotion: "joy",
//     bodyType: "any",
//     skinTone: "any",
//     gender: "any",
//     bestPose: "Dancing, expressive movement",
//     lightingTips: "Use colored lights or disco-style lighting.",
//     captionIdeas: ["Feel the beat!", "Dance it out 💃🕺", "Joy in every step!"],
//     hashtagSuggestions: ["#joyinmotion", "#dancevibes", "#freemovement"],
//     platforms: [{ name: "TikTok", bestPostTime: "8:00 PM" }],
//   },
//   {
//     emotion: "anger",
//     bodyType: "muscular",
//     skinTone: "dark",
//     gender: "man",
//     bestPose: "Standing with arms crossed",
//     lightingTips: "Use spotlight from side for dramatic shadows.",
//     captionIdeas: [
//       "Power doesn't need to yell.",
//       "Still. Strong. Unapologetic.",
//       "This is intensity.",
//     ],
//     hashtagSuggestions: ["#powerlook", "#boldpresence", "#standtall"],
//     platforms: [{ name: "YouTube", bestPostTime: "6:00 PM" }],
//   },
//   {
//     emotion: "surprise",
//     bodyType: "slim",
//     skinTone: "light",
//     gender: "any",
//     bestPose: "Caught mid-laugh or reaction",
//     lightingTips: "Flash lighting to freeze action.",
//     captionIdeas: [
//       "Wait—what?!",
//       "Well, that just happened 😳",
//       "Candid and real.",
//     ],
//     hashtagSuggestions: ["#realreaction", "#unfiltered", "#spontaneousmoment"],
//     platforms: [{ name: "Instagram", bestPostTime: "3:00 PM" }],
//   },
//   {
//     emotion: "neutral",
//     bodyType: "athletic",
//     skinTone: "medium",
//     gender: "man",
//     bestPose: "Straight posture with hands in pockets",
//     lightingTips: "Soft overhead lighting to avoid drama.",
//     captionIdeas: [
//       "Stay grounded.",
//       "Simple always wins.",
//       "Unmoved. Unbothered.",
//     ],
//     hashtagSuggestions: ["#lowkeymood", "#effortlessstyle", "#steadyvibes"],
//     platforms: [{ name: "LinkedIn", bestPostTime: "9:00 AM" }],
//   },
// ];

// const populateDatabase = async () => {
//   await mongoose.connect(process.env.MONGO_URI);
//   await Recommendation.deleteMany({});
//   await Recommendation.insertMany(recommendations);
//   console.log("Database populated with recommendations!");
//   mongoose.connection.close();
// };

// populateDatabase();
