apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
  labels:
    app: ai-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-worker
  template:
    metadata:
      labels:
        app: ai-worker
    spec:
      containers:
        - name: worker
          image: your-registry/ai-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: "http://ai-backend:5001"
            - name: WORKER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: WORKER_TOKEN
            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: ELEVENLABS_API_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: S3_BUCKET
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: S3_REGION
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: S3_ENDPOINT
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: MAX_AUDIO_SECONDS
              value: "20"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - name: http
              containerPort: 5001
          livenessProbe:
            exec:
              command: ["python", "/app/health_check.py"]
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["python", "/app/health_check.py"]
            initialDelaySeconds: 20
            periodSeconds: 30
